CoursesSystem/CoursesSystem.Web/Models/CoursesViewModels/CoursesViewModel.cs
using System.Collections.Generic;

namespace CoursesSystem.Web.Models.CoursesViewModels
{
    public class CoursesViewModel
    {
        public IEnumerable<CourseViewModel> Courses { get; set; }
    }
}

CoursesSystem/CoursesSystem.Web/Controllers/CoursesController.cs
using Bytes2you.Validation;
using CoursesSystem.Data.Models;
using CoursesSystem.DTO;
using CoursesSystem.Services.Data.Contracts;
using CoursesSystem.Utils.Contracts;
using CoursesSystem.Web.Models.CoursesViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CoursesSystem.Web.Controllers
{
    [Authorize]
    public class CoursesController : Controller
    {
        private readonly ICourseService courseService;
        private readonly IStudentService studentService;
        private readonly IStudentCourseService studentCourseService;
        private readonly IMappingProvider mapper;
        private readonly UserManager<Student> userManager;

        public CoursesController(
            ICourseService courseService,
            IStudentService studentService,
            IStudentCourseService studentCourseService,
            IMappingProvider mapper,
            UserManager<Student> userManager)
        {
            Guard.WhenArgument(courseService, "Course Service can not be null!").IsNull().Throw();
            Guard.WhenArgument(studentService, "Student Service can not be null!").IsNull().Throw();
            Guard.WhenArgument(studentCourseService, "StudentCourse Service can not be null!").IsNull().Throw();
            Guard.WhenArgument(mapper, "Mapper can not be null!").IsNull().Throw();
            Guard.WhenArgument(userManager, "User Manager").IsNull().Throw();

            this.courseService = courseService;
            this.studentService = studentService;
            this.studentCourseService = studentCourseService;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var model = new CoursesViewModel();

            var availableCourses = await this.courseService.GetAllAvailableCourses();
            Guard.WhenArgument(availableCourses, "Available Courses can not be null!").IsNull().Throw();

            var availableCoursesModel = mapper.ProjectTo<CourseDto, CourseViewModel>(availableCourses).ToList();
            Guard.WhenArgument(availableCoursesModel, "Available Courses can not be null!").IsNull().Throw();

            var studentId = this.userManager.GetUserId(this.HttpContext.User);
            var registeredCourses = await studentService.GetAllRegisteredCourses(studentId);
            Guard.WhenArgument(registeredCourses, "Registered Courses can not be null!").IsNull().Throw();

            foreach (var course in registeredCourses)
            {
                for (int i = 0; i < availableCoursesModel.Count(); i++)
                {
                    if (course.Id == availableCoursesModel[i].Id)
                    {
                        availableCoursesModel[i].IsRegistered = true;
                    }
                }
            }

            model.Courses = availableCoursesModel;

            return this.View(model);
        }

        public async Task<IActionResult> CoursesTables()
        {
            var model = new CoursesTablesViewModel();
            var studentId = this.userManager.GetUserId(this.HttpContext.User);

            var registeredCourses = await this.studentService.GetAllRegisteredCourses(studentId);
            Guard.WhenArgument(registeredCourses, "Registered Courses can not be null!").IsNull().Throw();

            var registeredCoursesModel = mapper.ProjectTo<CourseDto, CourseViewModel>(registeredCourses);
            Guard.WhenArgument(registeredCoursesModel, "Registered Courses can not be null!").IsNull().Throw();

            var notRegisteredCourses = await studentService.GetAllNonRegisteredCourses(studentId);
            Guard.WhenArgument(notRegisteredCourses, "Non-Registered Courses can not be null!").IsNull().Throw();

            var notRegisteredCoursesModel = mapper.ProjectTo<CourseDto, CourseViewModel>(notRegisteredCourses);
            Guard.WhenArgument(notRegisteredCourses, "Non-Registered Courses can not be null!").IsNull().Throw();

            model.RegisteredCourses = registeredCoursesModel;
            model.NotRegisteredCourses = notRegisteredCoursesModel;

            return View(model);
        }

        public IActionResult RegisterCourse([FromBody]CourseViewModel model)
        {
            var studentId = this.userManager.GetUserId(this.HttpContext.User);
            studentCourseService.AddCourseToStudent(model.Id, studentId);

            return Json($"{model.Name} course successfully registered!");
        }

        public IActionResult UnregisterCourse([FromBody]CourseViewModel model)
        {
            var studentId = this.userManager.GetUserId(this.HttpContext.User);
            studentCourseService.DeleteCourseFromStudent(model.Id, studentId);

            return Json($"{model.Name} course successfully unregistered!");
        }

        public async Task<IActionResult> ManageCourses()
        {
            var model = new CoursesViewModel();

            var availableCourses = await this.courseService.GetAllAvailableCourses();
            Guard.WhenArgument(availableCourses, "Available Courses can not be null!").IsNull().Throw();

            var availableCoursesModel = mapper.ProjectTo<CourseDto, CourseViewModel>(availableCourses);
            Guard.WhenArgument(availableCoursesModel, "Available Courses can not be null!").IsNull().Throw();

            model.Courses = availableCoursesModel;

            return View(model);
        }

        public async Task<IActionResult> Edit(Guid courseId)
        {
            var courseDto = await courseService.GetCourseById(courseId);
            Guard.WhenArgument(courseDto, "Course Dto can not be null!").IsNull().Throw();

            var courseModel = this.mapper.MapTo<CourseViewModel>(courseDto);
            Guard.WhenArgument(courseModel, "CourseModel can not be null!").IsNull().Throw();

            return View(courseModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CourseViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            var courseDto = await courseService.GetCourseById(model.Id);
            Guard.WhenArgument(courseDto, "Course Dto can not be null!").IsNull().Throw();

            if (model.Name != courseDto.Name)
            {
                this.courseService.EditCourseName(model.Id, model.Name);
            }

            if (model.Credits != courseDto.Credits)
            {
                this.courseService.EditCourseCredits(model.Id, model.Credits);
            }

            if (model.LecturerName != courseDto.LecturerName)
            {
                this.courseService.EditCourseLecturerName(model.Id, model.LecturerName);
            }

            return RedirectToAction("ManageCourses");
        }

        public IActionResult Delete(Guid courseId)
        {
            courseService.DeleteCourse(courseId);

            return RedirectToAction("ManageCourses");
        }

        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(CourseViewModel courseModel)
        {
            var courseToAdd = this.mapper.MapTo<CourseDto>(courseModel);
            Guard.WhenArgument(courseToAdd, "Course to add can not be null!").IsNull().Throw();

            courseService.AddCourse(courseToAdd);

            return RedirectToAction("ManageCourses");
        }
    }
}

CoursesSystem/CoursesSystem.Web/Views/Courses/Add.cshtml
@using CoursesSystem.Web.Models.CoursesViewModels;
@model CourseViewModel;

<form class="form-horizontal" asp-controller="Courses" asp-action="Add">
    <div class="form-group" style="visibility:hidden;">
        <label asp-for="@Model.Id" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="@Model.Id">
            <span class="text-danger" asp-validation-for="@Model.Id"></span>
        </div>
    </div>
    <div class="col-lg-8 col-lg-offset-2">
        <div class="form-group">
            <label asp-for="@Model.Name" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.Name">
                <span class="text-danger" asp-validation-for="@Model.Name"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="@Model.Credits" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.Credits">
                <span class="text-danger" asp-validation-for="@Model.Credits"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="@Model.LecturerName" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.LecturerName">
                <span class="text-danger" asp-validation-for="@Model.LecturerName"></span>
            </div>
        </div>

    </div>
    <div class="form-group">
        <div class="col-sm-offset-6 col-sm-6">
            <button class="btn btn-primary" type="submit" style="padding: 8px 25px; border-radius: 11%;">Add</button>
        </div>
    </div>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

CoursesSystem/CoursesSystem.Web/Views/Courses/CoursesTables.cshtml
@using CoursesSystem.Web.Models.CoursesViewModels;
@model CoursesTablesViewModel;

<div class="container">
    <div class="row">
        <div class="col-md-6 panel panel-primary filterable" style="margin-top: 4em; padding:0;">
            <div class="panel-heading" style="background-color: #1da1f2;border-color: #1da1f2;">
                <h3 class="panel-title">Registered Courses:</h3>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><h5>Name:</h5></th>
                        <th><h5>Registered:</h5></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var course in Model.RegisteredCourses)
                    {
                        <tr>
                            <td>@course.Name</td>
                            <td>
                                <i class="fa fa-check" style="color: green"></i>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <div class="col-md-6 panel panel-primary filterable" style="margin-top: 4em; padding:0;">
            <div class="panel-heading" style="background-color: #1da1f2;border-color: #1da1f2;">
                <h3 class="panel-title">Not registered Courses:</h3>
            </div>
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><h5>Name:</h5></th>
                        <th><h5>Registered:</h5></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var course in Model.NotRegisteredCourses)
                    {
                        <tr>
                            <td>@course.Name</td>
                            <td>
                                <i class="fa fa-times" style="color: red"></i>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>

CoursesSystem/CoursesSystem.Web/Views/Courses/Edit.cshtml
@using CoursesSystem.Web.Models.CoursesViewModels;
@model CourseViewModel;

<form class="form-horizontal" asp-controller="Courses" asp-action="Edit">
    <div class="form-group" style="visibility:hidden;">
        <label asp-for="@Model.Id" class="col-sm-2 control-label"></label>
        <div class="col-sm-10">
            <input type="text" class="form-control" asp-for="@Model.Id">
            <span class="text-danger" asp-validation-for="@Model.Id"></span>
        </div>
    </div>
    <div class="col-lg-8 col-lg-offset-2">
        <div class="form-group">
            <label asp-for="@Model.Name" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.Name">
                <span class="text-danger" asp-validation-for="@Model.Name"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="@Model.Credits" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.Credits">
                <span class="text-danger" asp-validation-for="@Model.Credits"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="@Model.LecturerName" class="col-sm-2 control-label"></label>
            <div class="col-sm-10">
                <input type="text" class="form-control" asp-for="@Model.LecturerName">
                <span class="text-danger" asp-validation-for="@Model.LecturerName"></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-6 col-sm-6">
            <button class="btn btn-primary" type="submit" style="padding: 8px 25px; border-radius: 11%;">EDIT</button>
        </div>
    </div>
</form>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

CoursesSystem/CoursesSystem.Web/Views/Courses/Index.cshtml
@using CoursesSystem.Web.Models.CoursesViewModels;
@model CoursesViewModel;

<div class="container">
    <div class="row">
        <div class="panel panel-primary filterable" style="margin-top: 4em;">
            <div class="panel-heading" style="background-color: #1da1f2;border-color: #1da1f2;">
                <h3 class="panel-title">Available Courses:</h3>
            </div>
            @{
                string messageId = string.Empty;
            }
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><h5>Id:</h5></th>
                        <th><h5>Name:</h5></th>
                        <th><h5>Credits:</h5></th>
                        <th><h5>Lecturer:</h5></th>
                        <th><h5>Registration:</h5></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var course in Model.Courses)
                    {
                        var registerBtn = $"regBtn-{course.Id}";
                        var unregisterBtn = $"unregBtn-{course.Id}";
                        var confirmBtn = $"confirmBtn-{course.Id}";
                        var confirmDelete = $"confirmDelete-{course.Id}";

                        var displayReg = "none";
                        var displayUnreg = "none";

                        if (!course.IsRegistered)
                        {
                            displayReg = "block";
                        }
                        else
                        {
                            displayUnreg = "block";

                        }

                        <tr>
                            <td>@course.Id</td>
                            <td>@course.Name</td>
                            <td>@course.Credits</td>
                            <td>@course.LecturerName</td>
                            <td>
                                <div class="modal fade" id="@confirmDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header" style="background-color: #1da1f2;">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                <h4 class="modal-title" id="myModalLabel" style="color: white;">Confirm</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>You are about to unregister for @course.Name course.</p>
                                                <p>Are you sure you want to proceed?</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button id="@confirmBtn" type="button" class="btn btn-danger btn-trigger" data-dismiss="modal"
                                                        parameter1="@course.Id"
                                                        parameter2="@course.Name">
                                                    Yes
                                                </button>
                                                <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <button id="@unregisterBtn" class="btn btn-danger btn-lg btn-block btn-sm btn-setmargin" type="button" data-toggle="modal" data-target="#@confirmDelete" style="display: @displayUnreg;">Unregister</button>

                                <button id="@registerBtn" class="btn btn-success btn-lg btn-block btn-sm btn-setmargin btn-trigger" type="button" style="display: @displayReg; margin-top:0;"
                                        parameter1="@course.Id"
                                        parameter2="@course.Name">
                                    Register
                                </button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <p class="message" data-message id="confirm-message"></p>
    </div>
</div>

@section Scripts{
    @await Html.PartialAsync("_ValidationScriptsPartial");
    <script src="~/js/reg-unreg.js"></script>
}

CoursesSystem/CoursesSystem.Web/Views/Courses/ManageCourses.cshtml
@using CoursesSystem.Web.Models.CoursesViewModels;
@model CoursesViewModel;

<div class="container">
    <div class="row">
        <p class="text-center" style="
        position: relative;
        top: 2.2em;
        right: 2.3em;">
            <a class="btn btn-success btn-lg btn-setmargin" form asp-controller="Courses" asp-action="Add">Add Course</a>
        </p>
        <div class="panel panel-primary filterable" style="margin-top: 4em;">
            <div class="panel-heading" style="background-color: #1da1f2;border-color: #1da1f2;">
                <h3 class="panel-title">All Courses:</h3>
            </div>
            @{
                string messageId = string.Empty;
            }
            <table class="table">
                <thead>
                    <tr class="filters">
                        <th><h5>Name:</h5></th>
                        <th><h5>Edit:</h5></th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var course in Model.Courses)
                    {
                        var editBtn = $"editBtn-{course.Id}";
                        <tr>
                            <td>@course.Name</td>
                            <td>
                                <div>
                                    <a class="btn btn-info" form asp-controller="Courses" asp-action="Edit" asp-route-courseid="@course.Id">EDIT</a>
                                    <a class="btn btn-danger" form asp-controller="Courses" asp-action="Delete" asp-route-courseid="@course.Id">DELETE</a>
                                </div>
                                @*<button id="@editBtn" class="btn btn-success btn-lg btn-block btn-sm btn-setmargin btn-trigger" type="button" style="visibility: @visibilityReg;"
                                            parameter1="@course.Id"
                                            parameter2="@course.Name"
                                            parameter3="@course.Credits"
                                            parameter4="@course.LecturerName">
                                        Edit
                                    </button>*@
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>